"""empty message

Revision ID: b2482054e451
Revises: f9db0823c9a5
Create Date: 2022-05-18 19:19:10.472707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2482054e451'
down_revision = 'f9db0823c9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('favorited_by', sa.Integer(), nullable=True))
    op.drop_constraint('character_ibfk_1', 'character', type_='foreignkey')
    op.create_foreign_key(None, 'character', 'user', ['favorited_by'], ['id'])
    op.drop_column('character', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('user', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.create_foreign_key('character_ibfk_1', 'character', 'user', ['user'], ['id'])
    op.drop_column('character', 'favorited_by')
    # ### end Alembic commands ###
