"""empty message

Revision ID: be2e239b2f3a
Revises: b2482054e451
Create Date: 2022-05-19 13:05:53.841427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2e239b2f3a'
down_revision = 'b2482054e451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorites', sa.String(length=999), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorites')
    # ### end Alembic commands ###
